# Scenario configuration for CARLA simulation in Town10
map = "Town10HD"

# Possible weathers: "ClearNoon", "CloudyNoon", "WetNoon", "MidRainyNoon", "HardRainNoon", "SoftRainNoon",
# "ClearSunset", "CloudySunset", "WetSunset", "MidRainSunset", "HardRainSunset", "SoftRainSunset"
weather = "SoftRainSunset"

# Seed for random number generator to ensure reproducibility. Mainly affects the random placement of pedestrians and vehicles.
random_seed = 42 

# Number of AI controlled vehicles and pedestrians in the simulation
ai_vehicles = 10
ai_pedestrians = 20

# Route as a list of Town10HD waypoints (x, y, z coordinates)
# The ego vehicle will follow these waypoints in order.
route = [
    [
        -18.726058959960938,
        28.132003784179688,
        0.0
    ],
    [
        11.273826599121094,
        28.215360641479492,
        0.0
    ],
    [
        68.04779052734375,
        69.83556365966797,
        0.0
    ],
    [
        97.61090087890625,
        101.64120483398438,
        0.0
    ],
    [
        59.3187370300293,
        130.6833953857422,
        0.0
    ],
    [
        -0.14773565530776978,
        130.2100830078125,
        0.0
    ],
    [
        -41.51115036010742,
        104.9453353881836,
        0.0
    ],
    [
        -17.022146224975586,
        69.72679138183594,
        0.0
    ],
    [
        44.02894973754883,
        52.548702239990234,
        0.0
    ],
    [
        67.413330078125,
        24.87133026123047,
        0.0
    ],
    [
        109.92987823486328,
        -9.334196090698242,
        0.0
    ],
    [
        37.81124496459961,
        -64.41241455078125,
        0.0
    ],
    [
        -15.301885604858398,
        -64.65406036376953,
        0.0
    ],
    [
        -52.33985137939453,
        -17.239608764648438,
        0.0
    ],
    [
        -78.04387664794922,
        16.467145919799805,
        0.0
    ],
    [
        -110.84508514404297,
        53.859619140625,
        0.0
    ],
    [
        -105.82670593261719,
        103.87220764160156,
        0.0
    ],
    [
        -61.74959182739258,
        136.83164978027344,
        0.0
    ],
    [
        -8.560596466064453,
        137.1585235595703,
        0.0
    ],
    [
        39.34989929199219,
        137.5718231201172,
        0.0
    ],
    [
        95.8235855102539,
        121.83549499511719,
        0.0
    ],
    [
        105.93690490722656,
        62.93906021118164,
        0.0
    ],
    [
        63.0753059387207,
        13.359233856201172,
        0.0
    ],
    [
        6.445520877838135,
        13.201887130737305,
        0.0
    ],
    [
        -66.79419708251953,
        12.998390197753906,
        0.0
    ],
    [
        -102.99175262451172,
        -22.180795669555664,
        0.0
    ],
    [
        -80.59050750732422,
        -56.58024978637695,
        0.0
    ],
    [
        17.412546157836914,
        -57.404083251953125,
        0.0
    ]
]